AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'

Rails:
  Enabled: true

Style/StringLiterals:
    EnforcedStyle: double_quotes
    Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: false

# Rails 5 only: https://github.com/bbatsov/rubocop/issues/3629
Rails/HttpPositionalArguments:
  Enabled: false

# Ruby 2.4 only
Lint/UnifiedInteger:
  Enabled: false
